name = "astro-ai"
compatibility_date = "2023-01-01"
send_metrics = false
node_compat = true
route = "astro-ai.connection-tribe.net/*"
workers_dev = false
compatibility_flags = ["nodejs_compat"]

[env.dev]
name = "astro-ai-dev-env"
workers_dev = true
compatibility_flags = ["nodejs_compat"]


# name = "t4-stack"
# compatibility_date = "2023-10-30"
# send_metrics = false
# node_compat = true
# route = "app.t4stack.com/*"
# workers_dev = false

# [env.preview]
# name = "t4-stack-preview"
# workers_dev = true
